ALTER TABLE solicitudes_filtro
  MODIFY COLUMN id INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Identificador único de la solicitud',
  MODIFY COLUMN persona_id_cliente VARCHAR(64) NULL COMMENT 'ID en tabla personas del cliente. NULL si es cliente nuevo sin historial',
  MODIFY COLUMN persona_id_aval VARCHAR(64) NULL COMMENT 'ID en tabla personas del aval. NULL si no existe en BD',
  MODIFY COLUMN no_servicio_cliente VARCHAR(64) NULL COMMENT 'Número de servicio CFE del cliente. Extraído del comprobante por OCR. Se usa para validar regla de domicilio (max 3 clientes / $30K por no_servicio)',
  MODIFY COLUMN no_servicio_aval VARCHAR(64) NULL COMMENT 'Número de servicio CFE del aval. Extraído del comprobante por OCR',
  MODIFY COLUMN curp_cliente VARCHAR(20) NULL COMMENT 'CURP del cliente extraído de la INE por OCR. Se usa para match certero de persona_id',
  MODIFY COLUMN curp_aval VARCHAR(20) NULL COMMENT 'CURP del aval extraído de la INE por OCR',
  MODIFY COLUMN nombre_cliente VARCHAR(192) NOT NULL COMMENT 'Nombre completo del cliente extraído de la INE por OCR (formato: Apellido_P Apellido_M Nombres)',
  MODIFY COLUMN nombre_aval VARCHAR(192) NOT NULL COMMENT 'Nombre completo del aval extraído de la INE por OCR',
  MODIFY COLUMN tabla_cargos_id INT(11) NOT NULL COMMENT 'FK a tabla_cargos.id — define monto, nivel, plazo, cargo y tarifa del crédito solicitado',
  MODIFY COLUMN monto_solicitado INT(11) NOT NULL COMMENT 'Monto del crédito solicitado en pesos',
  MODIFY COLUMN plazo_semanas INT(11) NOT NULL COMMENT 'Plazo del crédito: 16, 21 o 26 semanas',
  MODIFY COLUMN nivel VARCHAR(10) NOT NULL COMMENT 'Nivel del cliente: NUEVO, NOBEL, VIP, PREMIUM, LEAL, DIAMANTE',
  MODIFY COLUMN tipo_credito VARCHAR(32) NOT NULL DEFAULT 'renovacion' COMMENT 'Tipo de crédito: nuevo (sin historial) o renovacion (ya tuvo préstamos)',
  MODIFY COLUMN prestamo_anterior_id VARCHAR(32) NULL COMMENT 'PrestamoID del último crédito completado. Se llena durante revisión para validar reglas de renovación',
  MODIFY COLUMN monto_anterior INT(11) NULL COMMENT 'Monto otorgado del crédito anterior. Para validar aumento máximo de $2,000',
  MODIFY COLUMN nivel_anterior VARCHAR(10) NULL COMMENT 'Nivel que tenía en el crédito anterior. Para validar si puede subir de nivel',
  MODIFY COLUMN liquidado_con_descuento TINYINT(1) NULL COMMENT 'Si el crédito anterior se liquidó con descuento. Si es 1, NO puede subir de nivel en esta renovación',
  MODIFY COLUMN agencia VARCHAR(64) NOT NULL COMMENT 'Código de agencia donde se solicita el crédito (ej: AGE037)',
  MODIFY COLUMN gerencia VARCHAR(64) NOT NULL COMMENT 'Código de gerencia a la que pertenece la agencia (ej: GERE011)',
  MODIFY COLUMN semana INT(11) NOT NULL COMMENT 'Semana del calendario Xpress en que se creó la solicitud',
  MODIFY COLUMN anio INT(11) NOT NULL COMMENT 'Año en que se creó la solicitud',
  MODIFY COLUMN documentos LONGTEXT NULL COMMENT 'JSON con 4 documentos OCR: ine_cliente, comprobante_cliente, ine_aval, comprobante_aval. Cada uno tiene url, valida (bool) y datos_extraidos',
  MODIFY COLUMN data LONGTEXT NULL COMMENT 'JSON con metadata: solicitud_id_r2, snapshot de tabla_cargos al momento de crear, tokens OCR consumidos',
  MODIFY COLUMN docs_validos TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 si los 4 documentos fueron leídos correctamente por OCR. 0 si alguno falló',
  MODIFY COLUMN doc_invalido_detalle VARCHAR(255) NULL COMMENT 'Indica qué documento falló: ine_cliente, comprobante_cliente, ine_aval o comprobante_aval',
  MODIFY COLUMN status ENUM('pendiente','aprobada','rechazada','corregir') NOT NULL DEFAULT 'pendiente' COMMENT 'pendiente=sin revisar, aprobada=pasa filtrado, rechazada=no procede, corregir=devuelta al agente por docs/datos malos',
  MODIFY COLUMN reviewed_by VARCHAR(32) NULL COMMENT 'Usuario o sistema que realizó la revisión',
  MODIFY COLUMN reviewed_at TIMESTAMP NULL COMMENT 'Fecha y hora en que se revisó la solicitud',
  MODIFY COLUMN motivo_rechazo TEXT NULL COMMENT 'Razón del rechazo o de por qué se pide corrección. Requerido cuando status es rechazada o corregir',
  MODIFY COLUMN resultado_revision LONGTEXT NULL COMMENT 'JSON con datos duros de la validación: prestamo_anterior, validacion_monto, validacion_nivel, validacion_domicilio, validacion_docs, validacion_tabla_cargos',
  MODIFY COLUMN diagnostico TEXT NULL COMMENT 'Resumen legible para humanos de lo que se validó y encontró. Lo lee el gerente o quien revise la solicitud',
  MODIFY COLUMN tabla_cargos_id_sugerido INT(11) NULL COMMENT 'FK a tabla_cargos.id — plan alternativo sugerido cuando el solicitado no procede. Para que el agente ofrezca otra opción al cliente',
  MODIFY COLUMN created_by VARCHAR(32) NULL COMMENT 'Usuario que creó la solicitud (el agente de campo)',
  MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora de creación de la solicitud',
  MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Última modificación de la solicitud';
