-- ============================================================
-- solicitudes_raw: Copia exacta de solicitudes tal cual llegan
-- Propósito: Guardar el estado original de cada solicitud
--            al momento de ser insertada (antes de revisiones,
--            correcciones o cambios de status)
-- ============================================================

-- 1. Crear tabla espejo
CREATE TABLE IF NOT EXISTS solicitudes_raw (
    raw_id          INT AUTO_INCREMENT PRIMARY KEY,
    inserted_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Momento en que se copió a esta tabla',

    -- Columnas idénticas a solicitudes
    id                              VARCHAR(64) NOT NULL,
    agencia                         VARCHAR(32) NOT NULL,
    gerencia                        VARCHAR(32) NOT NULL,
    semana                          INT(11) NOT NULL,
    anio                            INT(11) NOT NULL,
    status                          VARCHAR(32) NOT NULL DEFAULT 'capturada',
    reviewed_by                     VARCHAR(64) DEFAULT NULL,
    reviewed_at                     DATETIME DEFAULT NULL,
    motivo_rechazo                  TEXT DEFAULT NULL,
    doc_invalido_detalle            TEXT DEFAULT NULL,
    diagnostico                     TEXT DEFAULT NULL,
    resultado_revision              LONGTEXT DEFAULT NULL,
    resultado_revision_version      VARCHAR(16) NOT NULL DEFAULT 'v1',
    prevalidacion_app               LONGTEXT DEFAULT NULL,
    prevalidacion_app_version       VARCHAR(16) NOT NULL DEFAULT 'v1',
    approval_requirements           LONGTEXT DEFAULT NULL,
    approval_requirements_version   VARCHAR(16) NOT NULL DEFAULT 'v1',
    tabla_cargos_id_sugerido        INT(11) DEFAULT NULL,
    tabla_cargos_snapshot           LONGTEXT DEFAULT NULL,
    review_version                  INT(11) NOT NULL DEFAULT 1,
    fecha_solicitud                 TIMESTAMP NULL DEFAULT NULL,
    created_by                      TEXT DEFAULT NULL,
    created_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- Cliente
    cliente_persona_id              VARCHAR(64) DEFAULT NULL,
    cliente_nombres                 TEXT DEFAULT NULL,
    cliente_ap_paterno              TEXT DEFAULT NULL,
    cliente_ap_materno              TEXT DEFAULT NULL,
    cliente_fecha_nacimiento        DATE DEFAULT NULL,
    cliente_genero                  TEXT DEFAULT NULL,
    cliente_estado_civil            TEXT DEFAULT NULL,
    cliente_num_hijos               INT(11) DEFAULT 0,
    cliente_estado_nacimiento       TEXT DEFAULT NULL,
    cliente_curp                    VARCHAR(18) DEFAULT NULL,
    cliente_rfc                     TEXT DEFAULT NULL,
    cliente_telefono                TEXT DEFAULT NULL,
    cliente_no_servicio             TEXT DEFAULT NULL,
    cliente_whatsapp                TINYINT(1) DEFAULT 0,
    cliente_email                   TEXT DEFAULT NULL,
    cliente_calle                   TEXT DEFAULT NULL,
    cliente_no_exterior             TEXT DEFAULT NULL,
    cliente_no_interior             TEXT DEFAULT NULL,
    cliente_colonia                 TEXT DEFAULT NULL,
    cliente_cp                      TEXT DEFAULT NULL,
    cliente_municipio               TEXT DEFAULT NULL,
    cliente_estado                  TEXT DEFAULT NULL,
    cliente_tipo_vivienda           TEXT DEFAULT NULL,
    cliente_residencia_desde        TEXT DEFAULT NULL,
    cliente_referencias             LONGTEXT DEFAULT NULL,
    cliente_ocupacion               TEXT DEFAULT NULL,
    cliente_empresa                 TEXT DEFAULT NULL,
    cliente_sueldo                  DECIMAL(10,2) DEFAULT 0.00,
    cliente_periodo_pago            TEXT DEFAULT NULL,
    cliente_ingresos_mensuales      DECIMAL(10,2) DEFAULT 0.00,
    cliente_egresos_mensuales       DECIMAL(10,2) DEFAULT 0.00,
    cliente_empleo_detalle          LONGTEXT DEFAULT NULL,
    cliente_ingresos_adicionales    LONGTEXT DEFAULT NULL,
    cliente_egresos_detalle         LONGTEXT DEFAULT NULL,
    cliente_activos                 LONGTEXT DEFAULT NULL,
    cliente_garantias               LONGTEXT DEFAULT NULL,

    -- Aval
    aval_persona_id                 VARCHAR(64) DEFAULT NULL,
    aval_nombres                    TEXT DEFAULT NULL,
    aval_ap_paterno                 TEXT DEFAULT NULL,
    aval_ap_materno                 TEXT DEFAULT NULL,
    aval_fecha_nacimiento           DATE DEFAULT NULL,
    aval_genero                     TEXT DEFAULT NULL,
    aval_estado_civil               TEXT DEFAULT NULL,
    aval_num_hijos                  INT(11) DEFAULT 0,
    aval_estado_nacimiento          TEXT DEFAULT NULL,
    aval_curp                       VARCHAR(18) DEFAULT NULL,
    aval_rfc                        TEXT DEFAULT NULL,
    aval_telefono                   TEXT DEFAULT NULL,
    aval_no_servicio                TEXT DEFAULT NULL,
    aval_whatsapp                   TINYINT(1) DEFAULT 0,
    aval_email                      TEXT DEFAULT NULL,
    aval_calle                      TEXT DEFAULT NULL,
    aval_no_exterior                TEXT DEFAULT NULL,
    aval_no_interior                TEXT DEFAULT NULL,
    aval_colonia                    TEXT DEFAULT NULL,
    aval_cp                         TEXT DEFAULT NULL,
    aval_municipio                  TEXT DEFAULT NULL,
    aval_estado                     TEXT DEFAULT NULL,
    aval_tipo_vivienda              TEXT DEFAULT NULL,
    aval_residencia_desde           TEXT DEFAULT NULL,
    aval_referencias                LONGTEXT DEFAULT NULL,
    aval_ocupacion                  TEXT DEFAULT NULL,
    aval_empresa                    TEXT DEFAULT NULL,
    aval_sueldo                     DECIMAL(10,2) DEFAULT 0.00,
    aval_periodo_pago               TEXT DEFAULT NULL,
    aval_ingresos_mensuales         DECIMAL(10,2) DEFAULT 0.00,
    aval_egresos_mensuales          DECIMAL(10,2) DEFAULT 0.00,
    aval_empleo_detalle             LONGTEXT DEFAULT NULL,
    aval_ingresos_adicionales       LONGTEXT DEFAULT NULL,
    aval_egresos_detalle            LONGTEXT DEFAULT NULL,
    aval_activos                    LONGTEXT DEFAULT NULL,
    aval_garantias                  LONGTEXT DEFAULT NULL,

    -- Crédito
    monto_solicitado                DECIMAL(10,2) DEFAULT 0.00,
    plazo_semanas                   INT(11) DEFAULT NULL,
    nivel_cliente                   VARCHAR(16) DEFAULT NULL,
    tarifa_semanal                  DECIMAL(8,2) DEFAULT 0.00,
    primer_pago                     DECIMAL(8,2) DEFAULT 0.00,
    cargo                           DECIMAL(8,2) DEFAULT 0.00,
    cargo_porcentaje                DECIMAL(8,2) DEFAULT 0.00,
    total_pagar                     DECIMAL(10,2) DEFAULT 0.00,
    tipo_credito                    VARCHAR(32) DEFAULT NULL,
    tabla_cargos_id                 INT(11) DEFAULT NULL,

    -- Documentos y GPS
    documentos                      LONGTEXT DEFAULT NULL,
    gps_lat                         DECIMAL(10,6) DEFAULT NULL,
    gps_lng                         DECIMAL(10,6) DEFAULT NULL,
    gps_timestamp                   VARCHAR(32) DEFAULT NULL,
    status_historial                LONGTEXT DEFAULT NULL,

    -- Índices para consulta
    INDEX idx_raw_solicitud_id (id),
    INDEX idx_raw_agencia (agencia),
    INDEX idx_raw_semana_anio (anio, semana)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Copia raw de solicitudes tal cual llegan al INSERT';


-- 2. Copiar solo los registros con status 'capturada'
INSERT INTO solicitudes_raw (
    id, agencia, gerencia, semana, anio, status,
    reviewed_by, reviewed_at, motivo_rechazo, doc_invalido_detalle,
    diagnostico, resultado_revision, resultado_revision_version,
    prevalidacion_app, prevalidacion_app_version,
    approval_requirements, approval_requirements_version,
    tabla_cargos_id_sugerido, tabla_cargos_snapshot, review_version,
    fecha_solicitud, created_by, created_at, updated_at,
    cliente_persona_id, cliente_nombres, cliente_ap_paterno, cliente_ap_materno,
    cliente_fecha_nacimiento, cliente_genero, cliente_estado_civil, cliente_num_hijos,
    cliente_estado_nacimiento, cliente_curp, cliente_rfc, cliente_telefono,
    cliente_no_servicio, cliente_whatsapp, cliente_email,
    cliente_calle, cliente_no_exterior, cliente_no_interior, cliente_colonia,
    cliente_cp, cliente_municipio, cliente_estado, cliente_tipo_vivienda,
    cliente_residencia_desde, cliente_referencias, cliente_ocupacion, cliente_empresa,
    cliente_sueldo, cliente_periodo_pago, cliente_ingresos_mensuales, cliente_egresos_mensuales,
    cliente_empleo_detalle, cliente_ingresos_adicionales, cliente_egresos_detalle,
    cliente_activos, cliente_garantias,
    aval_persona_id, aval_nombres, aval_ap_paterno, aval_ap_materno,
    aval_fecha_nacimiento, aval_genero, aval_estado_civil, aval_num_hijos,
    aval_estado_nacimiento, aval_curp, aval_rfc, aval_telefono,
    aval_no_servicio, aval_whatsapp, aval_email,
    aval_calle, aval_no_exterior, aval_no_interior, aval_colonia,
    aval_cp, aval_municipio, aval_estado, aval_tipo_vivienda,
    aval_residencia_desde, aval_referencias, aval_ocupacion, aval_empresa,
    aval_sueldo, aval_periodo_pago, aval_ingresos_mensuales, aval_egresos_mensuales,
    aval_empleo_detalle, aval_ingresos_adicionales, aval_egresos_detalle,
    aval_activos, aval_garantias,
    monto_solicitado, plazo_semanas, nivel_cliente, tarifa_semanal,
    primer_pago, cargo, cargo_porcentaje, total_pagar,
    tipo_credito, tabla_cargos_id,
    documentos, gps_lat, gps_lng, gps_timestamp, status_historial
)
SELECT
    id, agencia, gerencia, semana, anio, status,
    reviewed_by, reviewed_at, motivo_rechazo, doc_invalido_detalle,
    diagnostico, resultado_revision, resultado_revision_version,
    prevalidacion_app, prevalidacion_app_version,
    approval_requirements, approval_requirements_version,
    tabla_cargos_id_sugerido, tabla_cargos_snapshot, review_version,
    fecha_solicitud, created_by, created_at, updated_at,
    cliente_persona_id, cliente_nombres, cliente_ap_paterno, cliente_ap_materno,
    cliente_fecha_nacimiento, cliente_genero, cliente_estado_civil, cliente_num_hijos,
    cliente_estado_nacimiento, cliente_curp, cliente_rfc, cliente_telefono,
    cliente_no_servicio, cliente_whatsapp, cliente_email,
    cliente_calle, cliente_no_exterior, cliente_no_interior, cliente_colonia,
    cliente_cp, cliente_municipio, cliente_estado, cliente_tipo_vivienda,
    cliente_residencia_desde, cliente_referencias, cliente_ocupacion, cliente_empresa,
    cliente_sueldo, cliente_periodo_pago, cliente_ingresos_mensuales, cliente_egresos_mensuales,
    cliente_empleo_detalle, cliente_ingresos_adicionales, cliente_egresos_detalle,
    cliente_activos, cliente_garantias,
    aval_persona_id, aval_nombres, aval_ap_paterno, aval_ap_materno,
    aval_fecha_nacimiento, aval_genero, aval_estado_civil, aval_num_hijos,
    aval_estado_nacimiento, aval_curp, aval_rfc, aval_telefono,
    aval_no_servicio, aval_whatsapp, aval_email,
    aval_calle, aval_no_exterior, aval_no_interior, aval_colonia,
    aval_cp, aval_municipio, aval_estado, aval_tipo_vivienda,
    aval_residencia_desde, aval_referencias, aval_ocupacion, aval_empresa,
    aval_sueldo, aval_periodo_pago, aval_ingresos_mensuales, aval_egresos_mensuales,
    aval_empleo_detalle, aval_ingresos_adicionales, aval_egresos_detalle,
    aval_activos, aval_garantias,
    monto_solicitado, plazo_semanas, nivel_cliente, tarifa_semanal,
    primer_pago, cargo, cargo_porcentaje, total_pagar,
    tipo_credito, tabla_cargos_id,
    documentos, gps_lat, gps_lng, gps_timestamp, status_historial
FROM solicitudes
WHERE status = 'capturada';


-- 3. Trigger para copiar automáticamente cada nueva solicitud
DELIMITER $$

DROP TRIGGER IF EXISTS trg_solicitudes_raw_copy$$

CREATE TRIGGER trg_solicitudes_raw_copy
AFTER INSERT ON solicitudes
FOR EACH ROW
BEGIN
    INSERT INTO solicitudes_raw (
        id, agencia, gerencia, semana, anio, status,
        reviewed_by, reviewed_at, motivo_rechazo, doc_invalido_detalle,
        diagnostico, resultado_revision, resultado_revision_version,
        prevalidacion_app, prevalidacion_app_version,
        approval_requirements, approval_requirements_version,
        tabla_cargos_id_sugerido, tabla_cargos_snapshot, review_version,
        fecha_solicitud, created_by, created_at, updated_at,
        cliente_persona_id, cliente_nombres, cliente_ap_paterno, cliente_ap_materno,
        cliente_fecha_nacimiento, cliente_genero, cliente_estado_civil, cliente_num_hijos,
        cliente_estado_nacimiento, cliente_curp, cliente_rfc, cliente_telefono,
        cliente_no_servicio, cliente_whatsapp, cliente_email,
        cliente_calle, cliente_no_exterior, cliente_no_interior, cliente_colonia,
        cliente_cp, cliente_municipio, cliente_estado, cliente_tipo_vivienda,
        cliente_residencia_desde, cliente_referencias, cliente_ocupacion, cliente_empresa,
        cliente_sueldo, cliente_periodo_pago, cliente_ingresos_mensuales, cliente_egresos_mensuales,
        cliente_empleo_detalle, cliente_ingresos_adicionales, cliente_egresos_detalle,
        cliente_activos, cliente_garantias,
        aval_persona_id, aval_nombres, aval_ap_paterno, aval_ap_materno,
        aval_fecha_nacimiento, aval_genero, aval_estado_civil, aval_num_hijos,
        aval_estado_nacimiento, aval_curp, aval_rfc, aval_telefono,
        aval_no_servicio, aval_whatsapp, aval_email,
        aval_calle, aval_no_exterior, aval_no_interior, aval_colonia,
        aval_cp, aval_municipio, aval_estado, aval_tipo_vivienda,
        aval_residencia_desde, aval_referencias, aval_ocupacion, aval_empresa,
        aval_sueldo, aval_periodo_pago, aval_ingresos_mensuales, aval_egresos_mensuales,
        aval_empleo_detalle, aval_ingresos_adicionales, aval_egresos_detalle,
        aval_activos, aval_garantias,
        monto_solicitado, plazo_semanas, nivel_cliente, tarifa_semanal,
        primer_pago, cargo, cargo_porcentaje, total_pagar,
        tipo_credito, tabla_cargos_id,
        documentos, gps_lat, gps_lng, gps_timestamp, status_historial
    ) VALUES (
        NEW.id, NEW.agencia, NEW.gerencia, NEW.semana, NEW.anio, NEW.status,
        NEW.reviewed_by, NEW.reviewed_at, NEW.motivo_rechazo, NEW.doc_invalido_detalle,
        NEW.diagnostico, NEW.resultado_revision, NEW.resultado_revision_version,
        NEW.prevalidacion_app, NEW.prevalidacion_app_version,
        NEW.approval_requirements, NEW.approval_requirements_version,
        NEW.tabla_cargos_id_sugerido, NEW.tabla_cargos_snapshot, NEW.review_version,
        NEW.fecha_solicitud, NEW.created_by, NEW.created_at, NEW.updated_at,
        NEW.cliente_persona_id, NEW.cliente_nombres, NEW.cliente_ap_paterno, NEW.cliente_ap_materno,
        NEW.cliente_fecha_nacimiento, NEW.cliente_genero, NEW.cliente_estado_civil, NEW.cliente_num_hijos,
        NEW.cliente_estado_nacimiento, NEW.cliente_curp, NEW.cliente_rfc, NEW.cliente_telefono,
        NEW.cliente_no_servicio, NEW.cliente_whatsapp, NEW.cliente_email,
        NEW.cliente_calle, NEW.cliente_no_exterior, NEW.cliente_no_interior, NEW.cliente_colonia,
        NEW.cliente_cp, NEW.cliente_municipio, NEW.cliente_estado, NEW.cliente_tipo_vivienda,
        NEW.cliente_residencia_desde, NEW.cliente_referencias, NEW.cliente_ocupacion, NEW.cliente_empresa,
        NEW.cliente_sueldo, NEW.cliente_periodo_pago, NEW.cliente_ingresos_mensuales, NEW.cliente_egresos_mensuales,
        NEW.cliente_empleo_detalle, NEW.cliente_ingresos_adicionales, NEW.cliente_egresos_detalle,
        NEW.cliente_activos, NEW.cliente_garantias,
        NEW.aval_persona_id, NEW.aval_nombres, NEW.aval_ap_paterno, NEW.aval_ap_materno,
        NEW.aval_fecha_nacimiento, NEW.aval_genero, NEW.aval_estado_civil, NEW.aval_num_hijos,
        NEW.aval_estado_nacimiento, NEW.aval_curp, NEW.aval_rfc, NEW.aval_telefono,
        NEW.aval_no_servicio, NEW.aval_whatsapp, NEW.aval_email,
        NEW.aval_calle, NEW.aval_no_exterior, NEW.aval_no_interior, NEW.aval_colonia,
        NEW.aval_cp, NEW.aval_municipio, NEW.aval_estado, NEW.aval_tipo_vivienda,
        NEW.aval_residencia_desde, NEW.aval_referencias, NEW.aval_ocupacion, NEW.aval_empresa,
        NEW.aval_sueldo, NEW.aval_periodo_pago, NEW.aval_ingresos_mensuales, NEW.aval_egresos_mensuales,
        NEW.aval_empleo_detalle, NEW.aval_ingresos_adicionales, NEW.aval_egresos_detalle,
        NEW.aval_activos, NEW.aval_garantias,
        NEW.monto_solicitado, NEW.plazo_semanas, NEW.nivel_cliente, NEW.tarifa_semanal,
        NEW.primer_pago, NEW.cargo, NEW.cargo_porcentaje, NEW.total_pagar,
        NEW.tipo_credito, NEW.tabla_cargos_id,
        NEW.documentos, NEW.gps_lat, NEW.gps_lng, NEW.gps_timestamp, NEW.status_historial
    );
END$$

DELIMITER ;
